# Generated by Django 4.2.7 on 2025-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_role_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
