# Generated by Django 4.2.7 on 2025-06-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='name',
        ),
    ]
