# Generated by Django 4.2.7 on 2025-04-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_alter_actiondata_field_alter_actiondata_form_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlMaster',
        ),
        migrations.DeleteModel(
            name='ControlSubMaster1',
        ),
        migrations.DeleteModel(
            name='FieldMaster',
        ),
        migrations.DeleteModel(
            name='FormFieldMaster',
        ),
    ]
