# Generated by Django 4.2.7 on 2025-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0013_delete_controlmaster_delete_controlsubmaster1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='formfieldvalues',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
