# Generated by Django 4.2.7 on 2025-04-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0015_formgenerativefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='formfieldvalues',
            name='is_active',
        ),
    ]
