# Generated by Django 4.2.7 on 2025-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0017_sectionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
