# Generated by Django 4.2.7 on 2025-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0018_formfield_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='foriegn_key_form_id',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='is_primary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
