# Generated by Django 4.2.7 on 2025-06-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0019_formfield_foriegn_key_form_id_formfield_is_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='is_primary',
            new_name='primarykey',
        ),
    ]
