# Generated by Django 4.2.7 on 2025-06-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0020_rename_is_primary_formfield_primarykey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='primarykey',
            new_name='is_primary',
        ),
    ]
