# Generated by Django 4.2.7 on 2025-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0021_rename_primarykey_formfield_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='foriegn_key_form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
