# Generated by Django 4.2.7 on 2025-06-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0023_alter_formfield_foriegn_key_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIncrementNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField(blank=True, null=True)),
                ('increment', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_increment_id', to='Form.form')),
            ],
            options={
                'db_table': 'form_increment_no',
            },
        ),
    ]
