# Generated by Django 4.2.7 on 2025-06-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0026_formchaya_formfilechaya_formfieldvalueschaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldchaya',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvalueschaya',
            name='field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvalueschaya',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvalueschaya',
            name='form_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfilechaya',
            name='field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfilechaya',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfilechaya',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfilechaya',
            name='form_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
