# Generated by Django 4.2.7 on 2025-06-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0027_alter_formfieldchaya_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldchaya',
            old_name='form',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='formfieldvalueschaya',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='formfieldvalueschaya',
            old_name='form',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='formfilechaya',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='formfilechaya',
            old_name='file',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='formfilechaya',
            old_name='form',
            new_name='form_data_id',
        ),
        migrations.RenameField(
            model_name='formfilechaya',
            old_name='form_data',
            new_name='form_id',
        ),
    ]
