# Generated by Django 4.2.7 on 2025-06-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0028_rename_form_formfieldchaya_form_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldvalueschaya',
            old_name='form_data',
            new_name='form_data_id',
        ),
    ]
