# Generated by Django 4.2.7 on 2025-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0030_modulemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='candidate_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
