# Generated by Django 4.2.7 on 2025-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0031_candidatedetails_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='module',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
