# Generated by Django 4.2.7 on 2025-06-11 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0034_candidatefile_candidatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedetails',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='candidatefile',
            name='form_data',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='candidate_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_cand_value_id', to='Form.candidatedata'),
        ),
        migrations.AddField(
            model_name='candidatefile',
            name='candidate_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cand_data_id', to='Form.candidatedata'),
        ),
    ]
