# Generated by Django 4.2.7 on 2025-06-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0035_remove_candidatedetails_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
