# Generated by Django 4.2.7 on 2025-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0036_candidatedetails_primary_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulemaster',
            old_name='table_name',
            new_name='data_table',
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='file_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='index_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
