# Generated by Django 4.2.7 on 2025-06-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0037_rename_table_name_modulemaster_data_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedetails',
            old_name='candidate_data',
            new_name='form_data',
        ),
        migrations.RenameField(
            model_name='candidatefile',
            old_name='candidate_data',
            new_name='form_data',
        ),
    ]
