# Generated by Django 4.2.7 on 2025-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0038_rename_candidate_data_candidatedetails_form_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateData',
            new_name='candidate_data',
        ),
        migrations.RenameModel(
            old_name='CandidateDetails',
            new_name='candidate_details',
        ),
        migrations.RenameModel(
            old_name='Candidatefile',
            new_name='candidate_file',
        ),
    ]
