# Generated by Django 4.2.7 on 2025-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0039_rename_candidatedata_candidate_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_data',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
