# Generated by Django 4.2.7 on 2025-06-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0040_candidate_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_data',
            name='candidate_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
