# Generated by Django 4.2.7 on 2025-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0042_employee_file_employee_details_employee_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_details',
            name='foreign_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
