# Generated by Django 4.2.7 on 2025-07-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0043_candidate_details_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_details',
            name='foreign_key',
        ),
    ]
