# Generated by Django 4.2.7 on 2025-05-20 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0003_remove_districtmaster_city_citymaster_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_master',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.TextField(blank=True, null=True)),
                ('contact_person_email', models.TextField(blank=True, null=True)),
                ('contact_person_mobile_no', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='employee_designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_designation',
            },
        ),
        migrations.CreateModel(
            name='employee_site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_site',
            },
        ),
        migrations.CreateModel(
            name='sc_employee_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('employee_name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('handicapped', models.BooleanField(blank=True, default=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('mobile_no', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('uan_no', models.TextField(blank=True, null=True)),
                ('pf_no', models.TextField(blank=True, null=True)),
                ('esic', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('branch_name', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('account_no', models.TextField(blank=True, null=True)),
                ('account_holder_name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'sc_employee_master',
            },
        ),
        migrations.CreateModel(
            name='SettingMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_start_time', models.DateField(blank=True, null=True)),
                ('noti_end_time', models.DateField(blank=True, null=True)),
                ('no_of_notification', models.IntegerField(null=True)),
                ('no_of_employee', models.IntegerField(null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'setting_master',
            },
        ),
        migrations.CreateModel(
            name='site_master',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.TextField(blank=True, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.TextField(blank=True, null=True)),
                ('contact_person_email', models.TextField(blank=True, null=True)),
                ('contact_person_mobile_no', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'site_master',
            },
        ),
        migrations.CreateModel(
            name='SlotDetails',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.TextField(blank=True, null=True)),
                ('slot_description', models.CharField(blank=True, max_length=200, null=True)),
                ('shift_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('night_shift', models.BooleanField(blank=True, default=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'slot_details',
            },
        ),
        migrations.CreateModel(
            name='UserSlotDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_id', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_company_id', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shit_created', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_emp_id', to='Masters.sc_employee_master')),
                ('site_id', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_site_id', to='Masters.site_master')),
                ('slot_id', models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_slot_id', to='Masters.slotdetails')),
            ],
            options={
                'db_table': 'user_slot_details',
            },
        ),
    ]
