# Generated by Django 4.2.7 on 2025-05-20 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll', '0001_initial'),
        ('Masters', '0004_company_master_employee_designation_employee_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslotdetails',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_status_id', to='Payroll.payrollstatusmaster'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_relation', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='designation_id',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SlotDetails_designation_id', to='Payroll.designation_master'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='setting_id',
            field=models.ForeignKey(blank=True, db_column='setting_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SlotDetails_setting_id', to='Masters.settingmaster'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='site_id',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SlotDetails_site_id', to='Masters.site_master'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_status', to='Payroll.payrollstatusmaster'),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site_master',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_master_city_id', to='Masters.citymaster'),
        ),
        migrations.AddField(
            model_name='site_master',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_relation', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='site_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site_master',
            name='state_id',
            field=models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_master_site_master', to='Masters.statemaster'),
        ),
        migrations.AddField(
            model_name='site_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingmaster',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_relation', to='Masters.slotdetails'),
        ),
        migrations.AddField(
            model_name='settingmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_relation', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_employee_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='employment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_data', to='Masters.parameter_master'),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='state_id',
            field=models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_relation_state_id', to='Masters.statemaster'),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_employee_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee_site',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_site_relation', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='employee_site',
            name='site_id',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_site_relation', to='Masters.site_master'),
        ),
        migrations.AddField(
            model_name='employee_designation',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_designation_relation', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='employee_designation',
            name='designation_id',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_relation', to='Payroll.designation_master'),
        ),
        migrations.AddField(
            model_name='company_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
