# Generated by Django 4.2.7 on 2025-05-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_document'),
        ('Masters', '0005_userslotdetails_status_slotdetails_company_and_more'),
    ]

    operations = [
    ]
