# Generated by Django 4.2.7 on 2025-05-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0007_rename_pay_id_pay_type_id'),
        ('Masters', '0006_merge_20250523_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('designation_id', models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_relation', to='Payroll.designation_master')),
            ],
            options={
                'db_table': 'level_master',
            },
        ),
    ]
