# Generated by Django 4.2.7 on 2025-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_levelmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_employee_master',
            name='employment_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
