# Generated by Django 4.2.7 on 2025-05-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_alter_sc_employee_master_employment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_employee_master',
            old_name='employment_status',
            new_name='employment_status_id',
        ),
    ]
