# Generated by Django 4.2.7 on 2025-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_rename_employment_status_sc_employee_master_employment_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_master',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
