# Generated by Django 4.2.7 on 2025-05-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_parameter_master_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelmaster',
            name='designation_id',
        ),
    ]
