# Generated by Django 4.2.7 on 2025-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0012_sc_employee_master_aadharcard_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='state_name',
            field=models.TextField(null=True),
        ),
    ]
