# Generated by Django 4.2.7 on 2025-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_remove_attendancelog_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_master',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site_master',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
