# Generated by Django 4.2.7 on 2025-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0016_site_master_latitude_site_master_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='city_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
