# Generated by Django 4.2.7 on 2025-06-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_citymaster_city_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymaster',
            name='city_status',
        ),
    ]
