# Generated by Django 4.2.7 on 2025-07-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_remove_citymaster_city_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='site_id',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_employee', to='Masters.site_master'),
        ),
    ]
