# Generated by Django 4.2.7 on 2025-05-20 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0004_company_master_employee_designation_employee_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActMaster',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(blank=True, max_length=265, null=True)),
                ('act_menu_name', models.CharField(blank=True, max_length=265, null=True)),
                ('act_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_act_master',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'financial_year',
            },
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('slab_freq', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_tax', models.FloatField(blank=True, null=True)),
                ('tax_deducted', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('challan_month', models.CharField(blank=True, max_length=50, null=True)),
                ('challan_year', models.CharField(blank=True, max_length=50, null=True)),
                ('challan_period', models.CharField(blank=True, max_length=500, null=True)),
                ('employer_deduct', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act', models.ForeignKey(blank=True, db_column='act_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_act', to='Tax.actmaster')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_company', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_created_by', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_site', to='Masters.site_master')),
                ('state', models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_state', to='Masters.statemaster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_calculation',
            },
        ),
        migrations.CreateModel(
            name='SlabMaster',
            fields=[
                ('slab_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_slab', models.CharField(max_length=255)),
                ('slab_freq', models.CharField(max_length=255)),
                ('slab_status', models.FloatField(blank=True, null=True)),
                ('slab_year', models.CharField(max_length=255)),
                ('slab_months', models.CharField(max_length=255)),
                ('slab_months_challan', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_month', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act_id', models.ForeignKey(blank=True, db_column='act_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tax.actmaster')),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slab_tax_city', to='Masters.citymaster')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slab_created_by', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slab_tax_state', to='Masters.statemaster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slab_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_slab_master',
            },
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_deduct', models.FloatField(blank=True, null=True)),
                ('slab_status', models.FloatField(blank=True, null=True)),
                ('slab_type', models.CharField(blank=True, max_length=253, null=True)),
                ('slab_for', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('applicable_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('lwf_applicable', models.FloatField(blank=True, null=True)),
                ('employee_min_amount', models.IntegerField(blank=True, null=True)),
                ('special_LWF_calculation', models.FloatField(blank=True, null=True)),
                ('special_employer_contribution', models.IntegerField(blank=True, null=True)),
                ('employer_min_amount', models.IntegerField(blank=True, null=True)),
                ('Lwf_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('slab_applicable', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slabb_created_by', to=settings.AUTH_USER_MODEL)),
                ('slab_id', models.ForeignKey(blank=True, db_column='slab_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tax.slabmaster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slabb_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_slab',
            },
        ),
    ]
