# Generated by Django 4.2.7 on 2025-05-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0002_salaryunit_ratecardsalaryelement_salary_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_rate_card_details',
            name='salary_unit',
            field=models.ForeignKey(blank=True, db_column='salary_unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_rate_card_salary_unit', to='Payroll.salaryunit'),
        ),
    ]
