# Generated by Django 4.2.7 on 2025-05-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_employee_rate_card_details_salary_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryunit',
            old_name='value',
            new_name='unit_name',
        ),
    ]
