# Generated by Django 4.2.7 on 2025-05-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0005_alter_salaryunit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryunit',
            old_name='unit_name',
            new_name='name',
        ),
    ]
