# Generated by Django 4.2.7 on 2025-05-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0006_rename_unit_name_salaryunit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay_type',
            old_name='pay_id',
            new_name='id',
        ),
    ]
