# Generated by Django 4.2.7 on 2025-05-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_levelmaster'),
        ('Payroll', '0007_rename_pay_id_pay_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_card_relation',
            name='client_id',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_client_id', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='site_card_relation',
            name='level',
            field=models.ForeignKey(blank=True, db_column='level_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_level_id', to='Masters.levelmaster'),
        ),
    ]
