# Generated by Django 4.2.7 on 2025-05-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_remove_levelmaster_designation_id'),
        ('Payroll', '0008_site_card_relation_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_card_relation',
            name='level',
            field=models.ForeignKey(blank=True, db_column='lev', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_level_id', to='Masters.levelmaster'),
        ),
    ]
