# Generated by Django 4.2.7 on 2025-06-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0009_alter_site_card_relation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='classification',
            field=models.ForeignKey(blank=True, db_column='classification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_clasification', to='Payroll.basis_type'),
        ),
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='pay_type',
            field=models.ForeignKey(blank=True, db_column='pay_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_pay_type', to='Payroll.pay_type'),
        ),
    ]
