# Generated by Django 4.2.7 on 2025-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0010_alter_ratecardsalaryelement_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_element_master',
            name='visible',
            field=models.TextField(blank=True, null=True),
        ),
    ]
