# Generated by Django 4.2.7 on 2025-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=255, null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('candidates_answer', models.CharField(max_length=255, null=True)),
                ('is_right', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'candidates_answer',
            },
        ),
        migrations.CreateModel(
            name='CandidateTestMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('post', models.CharField(max_length=255, null=True)),
                ('marks_received', models.IntegerField(null=True)),
                ('out_of', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'candidate_test_master',
            },
        ),
        migrations.CreateModel(
            name='PostMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'post_master',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerMaster',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=255, null=True)),
                ('question', models.CharField(max_length=255, null=True)),
                ('choice1', models.CharField(max_length=255, null=True)),
                ('choice2', models.CharField(max_length=255, null=True)),
                ('choice3', models.CharField(max_length=255, null=True)),
                ('choice4', models.CharField(max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'question_answer_master',
            },
        ),
    ]
