# Generated by Django 4.2.7 on 2025-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetestmaster',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
