# Generated by Django 4.2.7 on 2025-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_candidatetestmaster_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswer',
            name='candidate_id',
            field=models.IntegerField(null=True),
        ),
    ]
