# Generated by Django 4.2.7 on 2025-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_candidatetestmaster_test_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='post',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatetestmaster',
            name='out_of',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatetestmaster',
            name='post',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionanswermaster',
            name='post',
            field=models.IntegerField(null=True),
        ),
    ]
