# Generated by Django 4.2.7 on 2025-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_candidateanswer_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('performance_level', models.CharField(max_length=255, null=True)),
                ('percentage_range', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'performance_master',
            },
        ),
        migrations.CreateModel(
            name='PostTopicMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(null=True)),
                ('topic_id', models.IntegerField(null=True)),
                ('no_of_questions', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'post_topic_mapping',
            },
        ),
        migrations.CreateModel(
            name='TopicMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'topic_master',
            },
        ),
        migrations.RenameField(
            model_name='questionanswermaster',
            old_name='post',
            new_name='topic_id',
        ),
        migrations.AddField(
            model_name='candidatetestmaster',
            name='it_marks_received',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidatetestmaster',
            name='it_out_of',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidatetestmaster',
            name='it_percentage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetestmaster',
            name='it_performance_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetestmaster',
            name='performance_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postmaster',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postmaster',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='postmaster',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postmaster',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
