# Generated by Django 4.2.7 on 2025-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_performancemaster_posttopicmapping_topicmaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemaster',
            old_name='percentage_range',
            new_name='performance_range',
        ),
        migrations.AddField(
            model_name='performancemaster',
            name='percentage_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='performancemaster',
            name='percentage_upto',
            field=models.IntegerField(null=True),
        ),
    ]
