# Generated by Django 4.2.7 on 2025-05-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_rename_percentage_range_performancemaster_performance_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemaster',
            old_name='performance_range',
            new_name='percentage_range',
        ),
    ]
