# Generated by Django 4.2.7 on 2025-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_rename_performance_range_performancemaster_percentage_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('candidate_id', models.IntegerField(null=True)),
                ('question_ids', models.TextField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'temporary_questions',
            },
        ),
    ]
