# Generated by Django 4.2.7 on 2025-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_questionanswermaster_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestmaster',
            name='candidate_id',
            field=models.IntegerField(null=True),
        ),
    ]
