# Generated by Django 4.2.7 on 2025-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_candidatetestmaster_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestmaster',
            name='form_data_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateanswer',
            name='candidate_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatetestmaster',
            name='candidate_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryquestion',
            name='candidate_id',
            field=models.TextField(null=True),
        ),
    ]
