# Generated by Django 4.2.7 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0003_workflow_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_matrix',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
