# Generated by Django 4.2.7 on 2025-06-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0005_history_workflow_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workflow_matrix',
        ),
    ]
