# Generated by Django 4.2.7 on 2025-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0006_delete_workflow_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.TextField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('step_name', models.TextField(blank=True, null=True)),
                ('button_type_id', models.IntegerField(blank=True, null=True)),
                ('button_act_details', models.IntegerField(blank=True, null=True)),
                ('role_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('step_id_flow', models.IntegerField(blank=True, null=True)),
                ('status_color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_matrix',
            },
        ),
    ]
