# Generated by Django 4.2.7 on 2025-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0007_workflow_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_matrix',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
