# Generated by Django 4.2.7 on 2025-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0008_alter_workflow_matrix_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_matrix',
            name='module',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
