# Generated by Django 4.2.7 on 2025-06-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0009_workflow_matrix_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history_workflow_details',
            new_name='recruitment_history_workflow_details',
        ),
        migrations.RenameModel(
            old_name='workflow_details',
            new_name='recruitment_workflow_details',
        ),
    ]
