# Generated by Django 4.2.7 on 2025-06-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0010_rename_history_workflow_details_recruitment_history_workflow_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recruitment_history_workflow_details',
            new_name='history_workflow_details',
        ),
        migrations.RenameModel(
            old_name='recruitment_workflow_details',
            new_name='workflow_details',
        ),
    ]
