# Generated by Django 4.2.7 on 2025-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0012_rec_history_workflow_details_rec_workflow_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec_history_workflow_details',
            name='candidate_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rec_history_workflow_details',
            name='history_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rec_history_workflow_details',
            name='history_created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rec_workflow_details',
            name='candidate_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rec_workflow_details',
            name='form_data_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rec_history_workflow_details',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rec_history_workflow_details',
            name='form_data_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rec_workflow_details',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
