# Generated by Django 4.2.7 on 2025-06-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0015_remove_attendancelog_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(null=True)),
                ('shift_id', models.IntegerField(null=True)),
                ('type_of_attendance', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'employee_shift_mapping',
            },
        ),
        migrations.CreateModel(
            name='ShiftMaster',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.TextField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('in_time_buffer', models.TimeField(null=True)),
                ('out_time_buffer', models.TimeField(null=True)),
                ('half_day_in_time', models.TimeField(null=True)),
                ('half_day_out_time', models.TimeField(null=True)),
                ('overtime', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_id_q1', to='Masters.company_master')),
                ('site_id', models.ForeignKey(db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_id_q1', to='Masters.site_master')),
            ],
            options={
                'db_table': 'shift_master',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_id_q2', to='Masters.company_master')),
            ],
            options={
                'db_table': 'attendance_log',
            },
        ),
    ]
