# Generated by Django 4.2.7 on 2025-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationMaster',
            fields=[
                ('user_relation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, max_length=255, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('shift_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_relation_master',
            },
        ),
    ]
