# Generated by Django 4.2.7 on 2025-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userrelationmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftmapping',
            name='company_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftmapping',
            name='location_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftmapping',
            name='shift_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
