# Generated by Django 4.2.7 on 2025-06-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employeeshiftmapping_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftmapping',
            name='user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
