# Generated by Django 4.2.7 on 2025-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeeshiftmapping_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('overtime_hours', models.DateTimeField(blank=True, null=True)),
                ('is_overtime', models.IntegerField(blank=True, default='0', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
