# Generated by Django 4.2.7 on 2025-06-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_dailyattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelationMaster',
        ),
        migrations.AlterModelTable(
            name='dailyattendance',
            table='daily_attendance',
        ),
    ]
