# Generated by Django 4.2.7 on 2025-06-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_userrelationmaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='date',
            new_name='atten_date',
        ),
        migrations.RenameField(
            model_name='dailyattendance',
            old_name='date',
            new_name='atten_date',
        ),
    ]
