# Generated by Django 4.2.7 on 2025-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_date_attendancelog_atten_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='status_change_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
