# Generated by Django 4.2.7 on 2025-06-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_dailyattendance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='status_change_time',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='status_change_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
