# Generated by Django 4.2.7 on 2025-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_dailyattendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='overtime_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
