# Generated by Django 4.2.7 on 2025-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_dailyattendance_overtime_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftmaster',
            old_name='in_time',
            new_name='in_shift_time',
        ),
        migrations.RemoveField(
            model_name='shiftmaster',
            name='out_time',
        ),
        migrations.AddField(
            model_name='shiftmaster',
            name='out_shift_time',
            field=models.TimeField(null=True),
        ),
    ]
