# Generated by Django 4.2.7 on 2025-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_in_time_shiftmaster_in_shift_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
