# Generated by Django 4.2.7 on 2025-07-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_dailyattendance_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('alert_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
