# Generated by Django 4.2.7 on 2025-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_earlyleaveapply_leaveapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecorrection',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
