# Generated by Django 4.2.7 on 2025-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_timecorrection_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='sync',
            field=models.TextField(blank=True, null=True),
        ),
    ]
