# Generated by Django 4.2.7 on 2025-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendancelog_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='company_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
