# Generated by Django 4.2.7 on 2025-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendancelog_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='in_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='out_time',
            field=models.DateField(null=True),
        ),
    ]
