# Generated by Django 4.2.7 on 2025-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendancelog_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
