# Generated by Django 4.2.7 on 2025-07-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_remove_citymaster_city_status'),
        ('attendance', '0020_alter_attendancelog_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_id_q2', to='Masters.company_master'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='out_time',
            field=models.TimeField(null=True),
        ),
    ]
