# Generated by Django 4.2.7 on 2025-07-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_attendancelog_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='atten_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='in_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='out_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
