# Generated by Django 4.2.7 on 2025-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_attendancelog_atten_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
