# Generated by Django 4.2.7 on 2025-07-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_remove_dailyattendance_a_remove_dailyattendance_p_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
    ]
