# Generated by Django 4.2.7 on 2025-07-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_remove_citymaster_city_status'),
        ('attendance', '0026_delete_dailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('atten_date', models.DateField(null=True)),
                ('is_present', models.IntegerField(blank=True, null=True)),
                ('is_absent', models.IntegerField(blank=True, null=True)),
                ('pl', models.IntegerField(blank=True, null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('cl', models.IntegerField(blank=True, null=True)),
                ('other_leave', models.IntegerField(blank=True, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('overtime_hours', models.IntegerField(blank=True, null=True)),
                ('is_overtime', models.IntegerField(blank=True, default='0', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comapny_att_id', to='Masters.company_master')),
                ('site_id', models.ForeignKey(db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_att_id', to='Masters.site_master')),
            ],
            options={
                'db_table': 'daily_attendance',
            },
        ),
    ]
