# Generated by Django 4.2.7 on 2025-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='cl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='is_absent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='is_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='pl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='sl',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
