# Generated by Django 4.2.23 on 2025-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_dailyattendance_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type_of_pay_element', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Salary'), ('O', 'Other')], max_length=1)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employee_payroll',
            },
        ),
    ]
