# Generated by Django 4.2.23 on 2025-09-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayroll',
            name='payslip',
            field=models.ForeignKey(db_column='pay_slip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_slip', to='attendance.payslip'),
        ),
    ]
