# Generated by Django 4.2.23 on 2025-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_employeepayroll_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
